---
abstract: "Parse DSN's, DBI connection strings."
author:
  - 'Torbjørn Lindahl <torbjorn.lindahl@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-ParseDSN
provides:
  DBIx::ParseDSN:
    file: lib/DBIx/ParseDSN.pm
    version: v0.9.3
  DBIx::ParseDSN::Default:
    file: lib/DBIx/ParseDSN/Default.pm
    version: v0.9.3
requires:
  Class::Load: 0.20
  DBI: 1.628
  Module::Load::Conditional: 0.54
  Moo: 1.004002
  MooX::Aliases: 0.001000
  MooX::HandlesVia: 0.001005
  Test::FailWarnings: 0.008
  Test::Most: 0.31
  Test::Perl::Critic: 1.02
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
  URI: 1.60
  utf8::all: 0.011
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: v0.9.3
