---
abstract: "Parse DSN's, DBI connection strings."
author:
  - 'Torbjørn Lindahl <torbjorn.lindahl@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.132140'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-ParseDSN
provides:
  DBIx::ParseDSN:
    file: lib/DBIx/ParseDSN.pm
    version: v0.9.2
  DBIx::ParseDSN::Default:
    file: lib/DBIx/ParseDSN/Default.pm
    version: v0.9.2
requires:
  Class::Load: 0.20
  DBI: 1.63
  Locale::Maketext::Lexicon: 0.96
  Module::Load::Conditional: 0.54
  Moose: 2.1005
  MooseX::Aliases: 0.10
  Test::FailWarnings: 0.008
  Test::Moose: 2.1005
  Test::Most: 0.31
  Test::Perl::Critic: 1.02
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
  URI: 1.60
  utf8::all: 0.011
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: v0.9.2
